spring.application.name=portfolio-be
file.upload-dir=C:\\WorkSpace\\DesignerPortfolioProject\\portfolio-be\\src\\main\\resources\\static\\media

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=a
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.show-sql=true
spring.h2.console.enabled=true


spring.liquibase.enabled: true
spring.liquibase.drop-first: false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema: public
logging.level.liquibase: DEBUG



# Database Connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA and Hibernate Settings
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true





